# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieInf',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=96)),
                ('movie_des', models.CharField(max_length=400)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=200)),
                ('writers', models.CharField(max_length=200)),
                ('movie_date', models.DateField()),
                ('movie_type', models.CharField(choices=[('Action', 'action movie'), ('Comedy', 'comedy movie'), ('History', 'historical movie'), ('Cartoon', 'cartoon movie'), ('Document', 'documentary movie'), ('Other', 'other movie')], default='Action', max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=32)),
                ('length', models.IntegerField()),
                ('alias', models.CharField(max_length=96)),
                ('currentRateValue', models.IntegerField(default=0)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='rateData',
            fields=[
                ('rate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate_title', models.CharField(max_length=64)),
                ('rate_score', models.IntegerField()),
                ('rate_comment', models.CharField(max_length=400)),
                ('see_or_not', models.BooleanField()),
                ('rate_date', models.DateField()),
                ('rateusefull', models.IntegerField()),
                ('rateuseless', models.IntegerField()),
                ('movie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rateApp.movieInf')),
            ],
        ),
        migrations.CreateModel(
            name='userInf',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('user_passwd', models.CharField(max_length=32)),
                ('user_alias', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='ratedata',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rateApp.userInf'),
        ),
    ]
